### ISSUE TITLE
A question about the Normalizer in DiffuserPipeline

### ISSUE THREAD

**Issue by Annycc** [leekwoon/rgg#1]
Thanks for your excellent work and I have been trying to reproduce and follow your work!

I downloaded the pretrained diffusion model **leekwoon/maze2d-large-v1-H384-T256** in Hugging Face and executed the make_data.py.  

An error occured indicating that **the Normalizer was not specified in model_index.json** and I found the class DiffuserPipeline needed a normalizer input. So I wonder what should I specify for the normalizer?
![image](https://github.com/leekwoon/rgg/assets/26813441/779cf10c-9425-46aa-b60a-16092debe2e0)

**Comment by leekwoon** [comment]
Thanks you for your interest in this work. Which version of the diffusers library you're currently using? I've tried to replicate the error you've described using diffusers version 0.12.1 but wasn't able to encounter the same issue.

(I've tested with following code below)

```
from rgg.utils import suppress_output, set_seed
from rgg.diffuser_utils import get_dataset
from rgg.pipeline_diffuser import (
    DiffuserPipeline, 
)

dataset = get_dataset('maze2d-large-v1')
print('[o] load dataset!')
normalizer = dataset.normalizer
pipeline = DiffuserPipeline.from_pretrained(
    'leekwoon/maze2d-large-v1-H384-T256',
    normalizer=normalizer,
).to('cuda')
```

**Comment by Annycc** [comment]
Thanks so much for your quick reply! The version of diffusers is 0.28.0. 
After I commented out the checking codes in class DiffusionPipeline, make_data.py is able to run.
![image](https://github.com/leekwoon/rgg/assets/26813441/16324368-9009-48a9-87c6-0c856bf74618)
Thansk again~
